# Generated by Django 4.0 on 2021-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('collection', models.IntegerField()),
                ('is_boots', models.BooleanField(default=0)),
                ('is_pants', models.BooleanField(default=0)),
                ('is_hat', models.BooleanField(default=0)),
                ('is_jacket', models.BooleanField(default=0)),
                ('image', models.ImageField(height_field=50, upload_to='products', width_field=32)),
            ],
        ),
    ]
