# Generated by Django 4.0 on 2022-01-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_hat',
            new_name='is_hats',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_jacket',
            new_name='is_jackets',
        ),
    ]
