# Generated by Django 4.0 on 2022-01-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_boots',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hats',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_jackets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_pants',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('b', 'boots'), ('j', 'jackets'), ('p', 'pants'), ('h', 'hats')], default='no_type', max_length=1),
        ),
    ]
