# Generated by Django 4.0 on 2022-01-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_is_boots_remove_product_is_hats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('boots', 'boots'), ('jackets', 'jackets'), ('pants', 'pants'), ('hats', 'hats')], default='no_type', max_length=15),
        ),
    ]
