# Generated by Django 4.0 on 2022-01-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_type_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='no description', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('boots', 'boots'), ('jackets', 'jackets'), ('pants', 'pants'), ('hats', 'hats')], default='no_category', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.IntegerField(default=0),
        ),
    ]
