# Generated by Django 4.0 on 2022-01-26 16:46

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_description_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=pathlib.PureWindowsPath('C:/Users/Alexander/Desktop/PythonProjects/Django-Pet-project/retailweb/media/products/Null.jpg'), upload_to='products/'),
        ),
    ]
