# Generated by Django 4.0 on 2022-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_boots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boots',
            name='size',
            field=models.CharField(choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=4),
        ),
    ]
