# Generated by Django 4.0 on 2022-02-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_boots_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boots',
        ),
    ]
