# Generated by Django 4.0 on 2022-03-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_boots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('size', models.CharField(choices=[('39', '39'), ('40', '40'), ('41', '41'), ('42', '42')], default='no size', max_length=4)),
            ],
            bases=('products.product',),
        ),
    ]
