# Generated by Django 4.0 on 2022-03-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_boots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
    ]
