# Generated by Django 4.0 on 2022-03-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
