# Generated by Django 4.0 on 2022-03-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='No size', max_length=4)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('size', models.CharField(choices=[('39', '39'), ('40', '40'), ('41', '41'), ('42', '42')], default='No size', max_length=4)),
            ],
            bases=('products.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='No description', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='C:\\Users\\Alexander\\Desktop\\PythonProjects\\Django-Pet-project\\retailweb/media/products/Null.jpg/', upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='Boots',
        ),
    ]
