# Generated by Django 4.0 on 2022-03-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_clothes_shoes_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackets',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes')),
                ('sleeve_length', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('products.clothes',),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.clothes')),
                ('leg_length', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('products.clothes',),
        ),
    ]
