# Generated by Django 4.0 on 2022-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_jackets_pants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackets',
            name='sleeve_length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pants',
            name='leg_length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
