# Generated by Django 4.0 on 2022-03-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_jackets_sleeve_length_alter_pants_leg_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size',
        ),
        migrations.AddField(
            model_name='clothes',
            name='Large_size_quantity',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='clothes',
            name='Medium_size_quantity',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='clothes',
            name='Small_size_quantity',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size_40_quantity',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size_41_quantity',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size_42_quantity',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
