# Generated by Django 4.0 on 2022-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_clothes_size_remove_shoes_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='Large_size_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='Medium_size_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='Small_size_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size_40_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size_41_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size_42_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
