# Generated by Django 4.0 on 2022-03-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_clothes_large_size_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
